#!/usr/bin/env node
// Score the editorial backlog and write content-ops/scorecard.md
// Priority = (Impact x Demand x Confidence) / Effort  (higher = sooner)
import { readFileSync, writeFileSync } from "node:fs";
import yaml from "js-yaml";

const CATEGORY_LABEL = {
  "platform-engineering-idp": "A Platform/IDP",
  "sre-reliability": "B SRE",
  "security-iam": "C Security/IAM",
  "data-mlops": "D Data/MLOps",
  "multicloud-enterprise": "E Multi-Cloud",
  finops: "F FinOps",
  "architecture-leadership": "G Leadership",
};

const doc = yaml.load(readFileSync("content-ops/backlog.yaml", "utf8"));
const topics = doc.topics ?? [];

const scored = topics
  .map((t) => ({
    ...t,
    score: +((t.impact * t.demand * t.confidence) / t.effort).toFixed(2),
  }))
  .sort((a, b) => {
    if (a.requiresOrg !== b.requiresOrg) return a.requiresOrg ? 1 : -1;
    return b.score - a.score;
  });

const band = (s) => (s >= 25 ? "Publish now" : s >= 12 ? "Soon" : s >= 5 ? "Backlog" : "Optional");

const lines = [
  "# Backlog Scorecard",
  "",
  "_Generated by `npm run score`. Do not edit by hand._",
  "",
  "Formula: `Priority = (Impact x Demand x Confidence) / Effort`. Org-required topics are pushed last.",
  "",
  "| # | Title | Category | Tier | Org | Im | De | Co | Ef | Score | Band |",
  "|---|---|---|---|:--:|--:|--:|--:|--:|--:|---|",
  ...scored.map((t) =>
    [
      `| ${t.id}`,
      t.title,
      CATEGORY_LABEL[t.category] ?? t.category,
      `T${t.proofTier}`,
      t.requiresOrg ? "yes" : "",
      t.impact,
      t.demand,
      t.confidence,
      t.effort,
      t.score,
      `${band(t.score)} |`,
    ].join(" | "),
  ),
  "",
];

writeFileSync("content-ops/scorecard.md", lines.join("\n"));
console.log(`Scored ${scored.length} topics -> content-ops/scorecard.md`);
